participant: Fluid

precice-config-file: precice-config.xml

interfaces:
- mesh: Fluid-Mesh-Faces
  locations: faceCenters
  patches:
  - flap
  write-data: Forces1
- mesh: Fluid-Mesh-Nodes
  locations: faceNodes
  patches:
  - flap
  read-data: Displacements1

FSIenabled: true

CHTenabled: false
disableCheckpointing: false
evaluateBoundaries: true
